package libraryManagementNew;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import net.proteanit.sql.DbUtils;

public class bookCheckIn extends javax.swing.JFrame {

	/**
	 * Creates new form checkout_books
	 */
	public bookCheckIn() {
		initComponents();
		checkInSearchActionPerformedDisplay();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		checkIntable = new javax.swing.JTable();
		checkInBtn = new javax.swing.JButton();
		Home = new javax.swing.JButton();
		checkInInput = new javax.swing.JTextField();
		checkInSearch = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(204, 255, 204));
		jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

		checkIntable.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null }, { null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } },
				new String[] { "Loan ID", "ISBN", "Borrower ID ", "Borrower Name" }));
		checkIntable.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				checkIntableMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(checkIntable);

		checkInBtn.setText("Check In");
		checkInBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				checkInBtnActionPerformed(evt);
			}
		});

		Home.setText("Home");
		Home.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				HomeActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(55, 55, 55)
								.addComponent(checkInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 103,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(46, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(21, 21, 21)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(45, 45, 45)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(checkInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(73, Short.MAX_VALUE)));

		checkInInput.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				checkInInputActionPerformed(evt);
			}
		});

		checkInSearch.setText("Search");
		checkInSearch.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				checkInSearchActionPerformed(evt);
			}
		});

		jLabel1.setText("Check In A Book");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(
								jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(23, 23, 23)
										.addComponent(checkInInput, javax.swing.GroupLayout.PREFERRED_SIZE, 260,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(101, 101, 101).addComponent(checkInSearch,
												javax.swing.GroupLayout.PREFERRED_SIZE, 111,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addGap(221, 221, 221).addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE, 149,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(checkInInput, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(checkInSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		pack();
	}// </editor-fold>

	public int LoanIdClicked;
	public String CardNoClicked;
	public String ISBNClicked;


	// when checkIn button is clicked
	private void checkInBtnActionPerformed(java.awt.event.ActionEvent evt) {
		if (LoanIdClicked == 0) {
			JOptionPane.showMessageDialog(null, "Please select a record to Check-In");
		} else if (LoanIdClicked != 0) {
			try {
				Connection connect = DBConnection.connect();
				Statement st = connect.createStatement();
				String query = "update BOOK set is_available=1 where isbn='" + ISBNClicked + "';";
				int res1 = st.executeUpdate(query);
				String query1 = "update book_loans set date_in=CURDATE() WHERE loan_id=" + LoanIdClicked + ";";
				int res2 = st.executeUpdate(query1);
				if (res1 == 1 && res2 == 1) {
					JOptionPane.showMessageDialog(null, "Book Check-In Completed!");

					checkIntable.setVisible(true);
					String inputString = checkInInput.getText();
					try {
						query = "select  bl.LOAN_ID,bl.Card_NO,bl.ISBN, b.last_name from book_loans bl left join borrower b on bl.CARD_no=b.Card_no where (bl.Card_no like '%"
								+ inputString + "%' or bl.isbn like '%" + inputString + "%' or b.last_name like '%" + inputString
								+ "%') and (bl.date_in is null);";
						ResultSet resSet = st.executeQuery(query);
						checkIntable.setModel(DbUtils.resultSetToTableModel(resSet));
						resSet.close();
					} catch (Exception e) {
						e.printStackTrace();
					}
				
				} else {
					JOptionPane.showMessageDialog(null, "Check-In Failed.");
				}
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}

	//checkin input search box text field
	private void checkInInputActionPerformed(java.awt.event.ActionEvent evt) {
	}

	// search for books to check in, enter any partial search string from loan_id,
	// card_no, last name or ISBN of the record.
	private void checkInSearchActionPerformed(java.awt.event.ActionEvent evt) {
		checkInSearchActionPerformedDisplay();
	}
	private void checkInSearchActionPerformedDisplay() {
		checkIntable.setVisible(true);
		String inputString = checkInInput.getText();
		try {
			// JDBC Connection
			Connection connect = DBConnection.connect();
			Statement st = connect.createStatement();
			String query;
			if(inputString == null) {
				 query = "select  bl.LOAN_ID,bl.Card_NO,bl.ISBN, b.last_name from book_loans bl left join borrower b on bl.CARD_no=b.Card_no";
			}
			else {
			 query = "select  bl.LOAN_ID,bl.Card_NO,bl.ISBN, b.last_name from book_loans bl left join borrower b on bl.CARD_no=b.Card_no where (bl.Card_no like '%"
					+ inputString + "%' or bl.isbn like '%" + inputString + "%' or b.last_name like '%" + inputString
					+ "%') and (bl.date_in is null);";
			}
			ResultSet resSet = st.executeQuery(query);
			checkIntable.setModel(DbUtils.resultSetToTableModel(resSet));
			resSet.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	// navigate to home
	private void HomeActionPerformed(java.awt.event.ActionEvent evt) {
		LibraryManagement home = LibraryManagement.home();
	}

	// when a record in the check-in table is clicked
	private void checkIntableMouseClicked(java.awt.event.MouseEvent evt) {
		int row = checkIntable.getSelectedRow();
		// to store the data in a Default table model vector
		DefaultTableModel defTableModel = (DefaultTableModel) checkIntable.getModel();
		LoanIdClicked = (int) defTableModel.getValueAt(row, 0);
		CardNoClicked = defTableModel.getValueAt(row, 1).toString();
		ISBNClicked = defTableModel.getValueAt(row, 2).toString();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(bookCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(bookCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(bookCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(bookCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new bookCheckIn().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton Home;
	private javax.swing.JButton checkInBtn;
	private javax.swing.JTextField checkInInput;
	private javax.swing.JButton checkInSearch;
	private javax.swing.JTable checkIntable;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration
}
