package libraryManagementNew;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

public class LibraryManagement extends javax.swing.JFrame {

	/**
	 * Creates new form libraryManagement
	 */
	public LibraryManagement() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		
		dateCheckedIn();

		jPanel1 = new javax.swing.JPanel();
		searchBooks = new javax.swing.JButton();
		borrower = new javax.swing.JButton();
		checkin = new javax.swing.JButton();
		fines = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE));

		searchBooks.setText("Search Books");
		searchBooks.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				searchBooksActionPerformed(evt);
			}
		});

		borrower.setText("Add Borrower");
		borrower.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				borrowerActionPerformed(evt);
			}
		});

		checkin.setText("Check-in");
		checkin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				checkinActionPerformed(evt);
			}
		});

		fines.setText("Fines");
		fines.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				finesActionPerformed(evt);
			}
		});

		jLabel1.setText("Library Management System");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(79, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup()
												.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(117, 117, 117))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addComponent(checkin).addGap(272, 272, 272))))
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(48, 48, 48).addComponent(searchBooks)
										.addGap(58, 58, 58)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(fines).addComponent(borrower)))
								.addGroup(layout.createSequentialGroup().addGap(154, 154, 154).addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(24, 24, 24)
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(36, 36, 36).addComponent(borrower)
										.addGap(34, 34, 34).addComponent(fines))
								.addGroup(layout.createSequentialGroup().addGap(35, 35, 35).addComponent(searchBooks)
										.addGap(35, 35, 35).addComponent(checkin)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>

	static searchBooks searchBooksObj = new searchBooks();
	static Borrower borrowerObj = new Borrower();
	static bookCheckIn checkInObj = new bookCheckIn();
	static Fines finesObj = new Fines();

	private void searchBooksActionPerformed(java.awt.event.ActionEvent evt) {
		searchBooksObj.setVisible(true);
		this.setVisible(false);
	}

	private void borrowerActionPerformed(java.awt.event.ActionEvent evt) {
		borrowerObj.setVisible(true);
		this.setVisible(false);
	}

	private void checkinActionPerformed(java.awt.event.ActionEvent evt) {
		checkInObj.setVisible(true);
		this.setVisible(false);
	}

	private void finesActionPerformed(java.awt.event.ActionEvent evt) {
		finesObj.setVisible(true);
		this.setVisible(false);
	}

	public static LibraryManagement home() {
		LibraryManagement home = new LibraryManagement();
		home.setVisible(true);
		finesObj.setVisible(false);
		checkInObj.setVisible(false);
		searchBooksObj.setVisible(false);
		borrowerObj.setVisible(false);
		return home;
	}

	public void dateCheckedIn() {
		try {
			System.out.println("inside datecheckedIn");
			Connection conn = DBConnection.connect();
			Statement stmt = conn.createStatement();
			String query = "select *,DATEDIFF(DATE_IN,DUE_DATE) AS DATDIFF from book_loans where DUE_DATE < DATE_IN;";
			ResultSet getSetRS = stmt.executeQuery(query);
			while (getSetRS.next()) {
				int loanId = getSetRS.getInt("loan_id");
				int dateDiff = getSetRS.getInt("DATDIFF");
				update(loanId, dateDiff);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	public void update(int loanId, int dateDiff) {
		 double fineAmt = dateDiff*0.25;
	        try{

	        Connection conn = DBConnection.connect();
	        Statement statmt = conn.createStatement();
	        String query = " INSERT INTO FINES (LOAN_ID, FINE_AMOUNT) VALUES("+loanId+","+fineAmt+") ON DUPLICATE KEY UPDATE FINE_AMOUNT = "+fineAmt+";";
	         int r = statmt.executeUpdate(query);
	        }
	        catch(Exception e)
	        {
	            e.printStackTrace();
	        }
	         
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LibraryManagement.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LibraryManagement.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LibraryManagement.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LibraryManagement.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LibraryManagement().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton borrower;
	private javax.swing.JButton checkin;
	private javax.swing.JButton fines;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JButton searchBooks;
	// End of variables declaration
}
