create schema library;
use library;
 CREATE TABLE library.BORROWER(
 CARD_NO VARCHAR(20) NOT NULL,
 SSN VARCHAR(11) NOT NULL,
 FIRST_NAME VARCHAR(20) NOT NULL,
 LAST_NAME VARCHAR(20) NOT NULL,
 EMAIL VARCHAR(255),
 ADDRESS VARCHAR(255) NOT NULL,
 CITY VARCHAR(200) NOT NULL,
 STATE VARCHAR(200) NOT NULL,
 PHONE CHAR(20),
 PRIMARY KEY(CARD_NO));
 
 create table book(
ISBN VARCHAR(10) NOT NULL,
TITLE VARCHAR(512) NOT NULL,
COVER VARCHAR(512) NOT NULL,
PUBLISHER VARCHAR(512) NOT NULL,
PAGES INT NOT NULL,
IS_AVAILABLE BOOLEAN NOT NULL DEFAULT TRUE,
CONSTRAINT PK_BOOK_ISBN
PRIMARY KEY(ISBN)
 );
 create table authors(
 AUTHOR_ID INT AUTO_INCREMENT,
 AUTHRO VARCHAR(512) NOT NULL,
 PRIMARY KEY (AUTHOR_ID)
 );
 CREATE TABLE BOOK_AUTHORS(
 AUTHOR_ID INT AUTO_INCREMENT,
 ISBN VARCHAR(10) NOT NULL,
 FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID),
 FOREIGN KEY(ISBN) REFERENCES BOOK(ISBN)
 );
 CREATE TABLE BOOK_LOANS(
 LOAN_ID INT AUTO_INCREMENT,
 CARD_NO VARCHAR(20),
 ISBN VARCHAR(10),
 DATE_OUT DATE,
 DUE_DATE DATE,
 DATE_IN DATE DEFAULT NULL,
 PRIMARY KEY(LOAN_ID),
 FOREIGN KEY(CARD_NO) REFERENCES BORROWER(CARD_NO),
 FOREIGN KEY(ISBN) REFERENCES BOOK(ISBN));
 
 CREATE TABLE FINES(
 LOAN_ID INT,
 FINE_AMOUNT FLOAT DEFAULT 0,
 FINE_PAID BOOLEAN DEFAULT FALSE,
 PRIMARY KEY (LOAN_ID),
 FOREIGN KEY(LOAN_ID) REFERENCES BOOK_LOANS(LOAN_ID)
 );
 
 